version: "3.9"

services:
  web:
    image: nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 80
    restart: unless-stopped
    networks:
      - simple-web
      - monitoring

  personalwebsite:
    image: ghcr.io/dwethmar/website:master
    ports:
      - "8808:80"
    restart: unless-stopped
    networks:
      - simple-web
      - monitoring

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --metrics 0.0.0.0:2000 run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    ports:
      - "2000:2000"
    depends_on:
      - web
      - personalwebsite
    restart: unless-stopped
    networks:
      - simple-web
      - monitoring

networks:
  simple-web:
  monitoring:
    driver: bridge